name: Move Forward
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04994628
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#387BC9'
    - '#FFFEE0'
    - '#010705'
    - '#B2B2B4'
    - '#7B7921'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
