name: Move Forward
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04994628
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141824'
    - '#ffffff'
    - '#aac2e2'
    - '#798897'
    - '#52312b'
  brandStrength: 0
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0
purpose: []
